version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
 build-and-publish:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     - run: docker build -t kklim/node-server .

     - run: docker push kklim/node-server
workflows:
      build-master:
        jobs:
          - build-and-publish:
              requires:
                 - test
              filters:
                branches:
                  only: master
          - test:
              filters:
                branches:
                  only: master
