version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.2
  
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: kklim/node-server
      - docker/push:
          image: kklim/node-server
workflows:
    build-and-test:
      jobs:
        - build-and-test

