jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: kklim/node-server
      - docker/publish:
          docker-password: 1loveprogramming
          docker-username: kklim
          image: kklim/node-server

orbs:
  docker: circleci/docker@1.0.2
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push
