version: 2.1
jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: kklim/node-server


orbs:
  docker: circleci/docker@1.0.2
  
workflows:
  build:
    jobs:
      - docker/publish:
          image: kklim/node-server
          docker-password: 1loveprogramming
          docker-username: kklim
