version: 2.1
jobs:
 build-and-publish:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     - run: docker build -t kklim/node-server .

     - run: docker push kklim/node-server

workflows:
      build-master:
        jobs:
          - build-and-publish:
              filters:
                branches:
                  only: master
