version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.2
  
jobs:
  test:
        executor:
            name: node/default
        steps:
            - checkout
            steps:
             - run: npm install
             - run: npm test
            
    build:       
        executor: docker/docker
        steps:
        - setup_remote_docker
        - checkout
        - docker/check
        - docker/build:
            image: kklim/node-server
        - docker/push:
            image: kklim/node-server

workflows:
    test:
      jobs:
        - test
        - build
