version: 2.1
orbs:
  node: circleci/node@1.1.6

  
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            
  build:
        environment:
          IMAGE_NAME: kklim/node-server
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Docker image
              command: docker build -t $IMAGE_NAME:latest .
              
  publish:
        environment:
          IMAGE_NAME: kklim/node-server
          DOCKERHUB_PASS: 1loveprogramming
          DOCKERHUB_USERNAME: kklim
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - setup_remote_docker
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker push $IMAGE_NAME:latest

workflows:
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master
          - publish:
              requires:
                - build
              filters:
                branches:
                  only: master
          - test



